### PR TITLE
Consolidate IResource path handling

### PR DESCRIPTION
**Pull request by tobous**
Consolidates the methods used to obtain different paths for an `IResource` to only `getProjectRelativePath()`.

This was done to simplify the `IResource` interface. Furthermore, most usages of the other path methods were not necessary. In general, the core should (almost always) only be interested in project relative paths. Any occurrences in the IDE implementations where absolute paths are necessary should work on the IDE-specific resource logic instead of `IResource` objects.

I would suggest reviewing the commit of this PR separately.

### Commits

<details><summary><b>[API] Remove `IResource.getLocation()`</b></summary>
<br>

Removes `IResource.getLocation()` as it deals with absolute paths.
Absolute paths should not be of interested for any logic in the Saros
core as such paths aren't applicable to all participants. If absolute
paths are needed in the IDE-specific Saros implementation logic, the
IDE-specific representation of the resource should be accessed directly
instead of using the Saros `IResource` interface for such purposes.

Removes the implementation for the Eclipse and IntelliJ implementation
as they were never used.

Removes the 'Override' tag from the Server implementation. The
implementation is kept for now as the rest of the resource logic heavily
relies on it.

</details>

<details><summary><b>[INTERNAL][CORE] Remove usage of `getFullPath()` from `CreateArchiveTask`</b></summary>
<br>

Removes the usage of `IResource.getFullPath()` from `CreateArchiveTask` by
unifying the passed lists of files and paths. Since there now always is
a one-to-one mapping, the error handling requiring the usage of
`getFullPath()` can be dropped.

</details>

<details><summary><b>[REFACTOR][CORE] Move file checksum logic to separate package</b></summary>
<br>

Moves the logic dealing with filesystem checksum caches into the
separate subpackage 'filesystem.checksum'. This makes it easier to
differentiate which classes belong to the filesystem implementation.

</details>

<details><summary><b>[INTERNAL] Add `IAbsolutePathResolver` to use for checksum cache</b></summary>
<br>

Adds the helper `IAbsolutePathResolver` allowing checksum cache
implementations to resolve the absolute path for an `IFile`. This was
explicitly added to a separate interface to deter the general usage of
absolute path conversions for Saros resources. The checksum cache is one
of the rare cases where we are actually interested in the absolute path
of a resource.

Adds the Eclipse implementation `EclipseAbsolutePathResolver` using
`IResource.getLocation()` to obtain the absolute path for resources.

</details>

<details><summary><b>[INTERNAL] Use `IAbsolutePathResolver` in `FileSystemChecksumCache`</b></summary>
<br>

Replaces calls to `IResource.getFullPath()` with calls to
`IAbsolutePathResolver.getAbsolutePath(IFile)` in `FileSystemChecksumCache`.

This was done to be able to remove the method `IResource.getFullPath()`
from the interface as part of the interface consolidation. The aim is to
only have a single path method that only returns the project-relative
path.

Furthermore, with the current `IResource` implementations, the result of
`getFullPath()` were not always usable to uniquely identify a shared
resource. Using the absolute path guarantees that the resource is
uniquely identified in the local filesystem. This is a valid approach in
this case as the cache is only used locally.

</details>

<details><summary><b>[INTERNAL] Remove `IResource.getFullPath()`</b></summary>
<br>

Removes `IResource.getFullPath()`. This was done to consolidate the
`IResource` interface to only contain one method to obtain the path for a
resource.

Removes the remaining usages of `getFullPath()` from the core. All
remaining calls in the core were merely for logging purposes.

Removes the implementation for the Eclipse and IntelliJ implementation.

Removes the 'Override' tag from the Server implementation as the method
is still used in separate places in the Server resource implementation.
This will be cleaned up as part of the resource redesign. Adjusts any
calls to the method by unboxing the `IResource` object beforehand to
directly access the server resource implementation.

</details>

### CODE REVIEW

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- eclipse/src/saros/filesystem/checksum/EclipseAbsolutePathResolver.java  2
- core/src/saros/filesystem/checksum/NullChecksumCache.java  1
- core/src/saros/filesystem/checksum/FileSystemChecksumCache.java  17
- core/test/junit/saros/filesystem/checksum/FileSystemChecksumCacheTest.java  1
- eclipse/src/saros/filesystem/checksum/FileContentNotifierBridge.java  8
         

Complexity decreasing per file
==============================
+ core/src/saros/negotiation/CreateArchiveTask.java  -5
         

Clones removed
==============
+ intellij/src/saros/intellij/filesystem/IntelliJFileImpl.java  -1
+ intellij/src/saros/intellij/filesystem/IntelliJFolderImpl.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5442568&bid=17847231)

**Comment by tobous** [comment]
Rebased onto current base branch without any interaction.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- eclipse/src/saros/filesystem/checksum/FileContentNotifierBridge.java  8
- core/src/saros/filesystem/checksum/FileSystemChecksumCache.java  17
- eclipse/src/saros/filesystem/checksum/EclipseAbsolutePathResolver.java  2
- core/src/saros/filesystem/checksum/NullChecksumCache.java  1
- core/test/junit/saros/filesystem/checksum/FileSystemChecksumCacheTest.java  1
         

Complexity decreasing per file
==============================
+ core/src/saros/negotiation/CreateArchiveTask.java  -5
         

Clones removed
==============
+ intellij/src/saros/intellij/filesystem/IntelliJFileImpl.java  -1
+ intellij/src/saros/intellij/filesystem/IntelliJFolderImpl.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5442568&bid=17847231)

**Comment by tobous** [comment]
Rebased onto current master without any interaction.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- eclipse/src/saros/filesystem/checksum/EclipseAbsolutePathResolver.java  2
- core/src/saros/filesystem/checksum/FileSystemChecksumCache.java  17
- eclipse/src/saros/filesystem/checksum/FileContentNotifierBridge.java  8
- core/test/junit/saros/filesystem/checksum/FileSystemChecksumCacheTest.java  1
- core/src/saros/filesystem/checksum/NullChecksumCache.java  1
         

Complexity decreasing per file
==============================
+ core/src/saros/negotiation/CreateArchiveTask.java  -5
         

Clones removed
==============
+ intellij/src/saros/intellij/filesystem/IntelliJFolderImpl.java  -1
+ intellij/src/saros/intellij/filesystem/IntelliJFileImpl.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5442568&bid=17847231)

**Pull request merged**
