### PR TITLE
[INTERNAL][HTML WB] Setup development environment

### PR DESCRIPTION
**Pull request by AbdBarho**
bundling the whiteboard is done through webpack, using the babel plugin to support older browsers.

the `package.json` file contains the dependencies of the whiteboard, as well as the scripts to setup and build it.

`.babelrc` is used to configure the babel plug in

`.eslint.json` configuration file for the linter

`webpack.config.js` the whiteboard bundler configuration.

setting up the development environment before starting the development is done with the command `npm run setup`
while developing the whiteboard the developer should use `npm run dev`
when building for deployment `npm run build`

### CODE REVIEW

**Comment by AbdBarho** [comment]
Hey @m273d15, for installing the whiteboard dependencies either `git` or `python` is needed in the environment, is this possible to setup? the `git` option is guaranteed to work as I have used it locally already.

**Comment by m273d15** [comment]
@AbdBarho If you need something new in the environment you have to adjust the docker image ci_build in the repository dockerfiles. You have to change [`setup_ci_build.sh`](https://github.com/saros-project/dockerfiles/blob/master/src/setup_ci_build.sh) and add the packages (`python2` or `git`) to the command `apk add --no-cache npm`.
This could lead to a new command `apk add --no-cache npm python2`. You should have the permissions to create a PR in this repo.

**Comment by tobous** [comment]
@AbdBarho We decided against committing the package-lock.json to the repo. Please add it to the .gitignore and remove it from this PR.
For a short summary of the reasoning behind the decision, you can have a look at the discussion in .gitignore of https://github.com/saros-project/saros/commit/f35f1335863a0121d978e75778bb6785925550f1#diff-a084b794bc0759e7a6b77810e01874f2.
If you disagree, please give your reasoning and the topic can be discussed again.

**Comment by AbdBarho** [comment]
@tobous  Yes thank you, I was sceptical at the beginning about uploading the file, but I did it anyways, better safe than sorry.

the file is removed now and `.gitignore` is updated

**Comment by AbdBarho** [comment]
@m273d15 yes, isnt it already activated? I checked the build log and no errors were thrown

**Comment by m273d15** [comment]
@AbdBarho No, you simply created a PR, which is tested. You have to merge this PR. As next step the current master has to be tagged (I don't know whether you have the permissions to tag the master) and this tag will be used to tag the next image. This new tag can be used in the travis config.

**Comment by m273d15** [comment]
@AbdBarho This PR now uses the new images with a pre-installed git.

**Comment by AbdBarho** [comment]
@m273d15 yes, thank you very much, the build is new successful, I will start working on the other patches.

**Pull request merged**
