### PR TITLE
[FIX] #922 Ignore .git directory for Saros sessions

### PR DESCRIPTION
**Pull request by tobous**
Adjusts the IResource.isIgnored() implementations for Saros/E and
Saros/I to see any resource located in a '.git' directory and the
directory itself as ignored.

This is a temporary workaround to ensure that Saros does not destroy
data by overwriting the local git configuration as part of the project
negotiation.

### CODE REVIEW

**Comment by tobous** [comment]
This fix explicitly only looks at the project-relative paths. As a result, a user could theoretically still share a sub-directory of a `.git` directory.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5378012&bid=17634994)

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5378012&bid=17634994)

**Comment by m273d15** [comment]
> This is a temporary workaround

The real solution is using the future ignore mechanism you want to implement?

**Comment by tobous** [comment]
> > This is a temporary workaround
> 
> The real solution is using the future ignore mechanism you want to implement?

Yes, that was my thought behind the comment.

With this workaround, it seems weird to me to single out git (I know it is the most widely used VCS, but still) by implementing a hard-coded exclusion rule.

So, as part of the git integration for the new exclusion service, git configuration resources should be ignores by default if this option is chosen. This logic would then replace the hard-coded check implemented in the PR. 

This would, again, leave more room for user error (e.g. not selecting the option to use git-based exclusions), but it still seems like a better solution to me. But that can be discussed in more detail in the PR replacing this logic.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5378012&bid=17634994)

**Pull request merged**
