### PR TITLE
[STF] Add RemoteHTMLWidgets

### PR DESCRIPTION
**Pull request by jafey**
This pull request contains all classes the htmlBot uses for interacting with the HTML-GUI.

Also there are some basic tests which uses the htmlBot (AddContactTest & StartSessionWizardTest)

### CODE REVIEW

**Comment by tobous** [comment]
Why are some commits present twice in this PR? For example, "
[STF] Add RemoteHTMLCheckbox and RemoteHTMLRadioGroup" is present with the commit id 8ecd14f93700f805b94234556d4cc709935e52e9 and a2d2e0d2b82528f50f32a939ded7198585c1df13. Please clean up the commit history for this PR.

**Comment by jafey** [comment]
@tobus I followed the git instructions to resolve merge conflicts and after I pushed the merge to this branch git created new commits in the PR automatically.

What I did is:
```
git fetch origin
git checkout -b pr/stf-project origin/pr/stf-project
git merge master
git push
```

**Comment by tobous** [comment]
Commits for the Saros repository should only contain Unix line endings. It looks like all of your changes have Windows line endings.
Please add the correct `core.autocrlf` setting to your git config. You can have a look at the corresponding section on https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration to figure out the needed setting for your operating system. (For Windows, this should be "core.autocrlf=true".)

After adding this setting, you will have to to adjust all of your commits. The same applies to your commits in #173, #174, #175.

Please use this opportunity to
- split #172 (this PR) into multiple stacked PRs. Currently, this is way to much code to review properly.
- split #175 into multiple PRs. See my comment in the PR about separating changes from refactorings. The base PR of this PR-chain/stack should point to the last PR of the stack for #172.
- split #173 into two (stacked) PRs.

A basic explanation on how we currently handle stacked PRs is given in the initial comment of the ticket #133. If you don't agree with this approach or have a better one, please add to the discussion.

**Comment by tobous** [comment]
As a side note when creating new PRs:

If you are of the opinion that multiple commits should be part of the same PR, you will have to keep the list of commits clean until committing. This means you can't add new commits for fixing stuff noted during the review or for merging with the master, etc.

We don't want to squash multiple commits as this would remove the separation of concerns and worsen readability, which were the reasons to create multiple commits in the first place, meaning we would have to rebase the commits during the merging of the PR.

This means all changes during the review process will have to be done by amending an existing commit and then cherry-picking any other commits in the PR (in the right order) that are based on the changed commit. After all changes are done locally, the changes will have to be force-pushed onto the GitHub branch. Force-pushing is risky as it will override the existing commits/history of the PR, meaning mistakes while amending/cherry-picking commits are hard to revert.

This is why, with our current workflow, I would generally recommend to create PRs only containing single commits (initially). This way, any changes can be done with additional commits that are then squashed when merging the PR.
Furthermore, force-pushing messes up the PR overview a bit, making it harder to get an overview what happened during the review.

**Comment by jafey** [comment]
@tobus please look at the new branches and pull request i made. Is it okay now.

**Comment by tobous** [comment]
PR #186 still has issues with line endings (in IRemoteHTMLInputField and RemoteHTMLInputField). There also seem to be problems with line endings in the following changes in the chain (I only looked at a few at random).

Also, as noted in #186, please choose the current master as the base of all of your PR chains as Kelvin recently added a commit that should enforce LF endings for new commits. I don't know what happens when you rebase existing commits, so you might have to adjust these yourself.

**Pull request closed without merging**
