### PR TITLE
[UI][E] Remove access to partial sharing feature

### PR DESCRIPTION
**Pull request by tobous**
Removes the access to the partial sharing feature from the Saros/E UI.

Restricts the "Share Projects..." and "Add to Saros session" pop-up
to project entries.

Adjusts the resource sharing dialog to only show project entries.
This adjustment introduces a new bug where elements that are not
initially selected still have the arrow to extend their child content,
even though they have no child entries. If the arrow is clicked, it
disappears. This bug is acceptable in my opinion as this is only a
temporary workaround until the reference point sharing logic has been
introduced, as the GUI will have to be reworked at that point anyways.

Subsequently set tests reliant on the full functionality of the resource
selection dialog to 'Ignored'.

Removes the STF tests covering partial sharing or logic related to
partial sharing.

Moves a test erroneously located in the partial sharing tests to the
package 'encoding' and renames the test class to better represent what
is actually tested.

### CODE REVIEW

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- stf.test/test/saros/stf/test/encoding/ChangeShareFilesEncodingTest.java  1
         

Clones removed
==============
+ stf/test/saros/stf/test/stf/view/explorer/PackageExplorerViewDecoratorTest.java  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5222987&bid=17124209)

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- stf.test/test/saros/stf/test/encoding/ChangeShareFilesEncodingTest.java  1
         

Clones removed
==============
+ stf/test/saros/stf/test/stf/view/explorer/PackageExplorerViewDecoratorTest.java  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5222987&bid=17124209)

**Comment by tobous** [comment]
@srossbach @m273d15 This is ready to merge in my opinion (and you both seem to agree).

Any issues with this being merged before the upcoming Saros/E release (meaning the release would not have access to the partial sharing feature)?

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- stf.test/test/saros/stf/test/encoding/ChangeShareFilesEncodingTest.java  1
         

Clones removed
==============
+ stf/test/saros/stf/test/stf/view/explorer/PackageExplorerViewDecoratorTest.java  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5222987&bid=17124209)

**Comment by tobous** [comment]
Rebased onto current master, without any interactions.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- stf.test/test/saros/stf/test/encoding/ChangeShareFilesEncodingTest.java  1
         

Clones removed
==============
+ stf/test/saros/stf/test/stf/view/explorer/PackageExplorerViewDecoratorTest.java  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5222987&bid=17124209)

**Comment by tobous** [comment]
Rebased onto current master without any interaction.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- stf.test/test/saros/stf/test/encoding/ChangeShareFilesEncodingTest.java  1
         

Clones removed
==============
+ stf/test/saros/stf/test/stf/view/explorer/PackageExplorerViewDecoratorTest.java  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5222987&bid=17124209)

**Pull request merged**
