### PR TITLE
Migrate inner classes to reference points (ref-point migration 2/5)

### PR DESCRIPTION
**Pull request by tobous**
Migrates the internal logic (and some of the easier UI logic) to use the new reference point based resource implementations.

I would suggest reviewing this PR commit by commit.

#### [INTERNAL][I] Remove ModuleTypeNegotiationHook as it is no longer needed

Removes ModuleTypeNegotiationHook as module types are no longer of
interest for Saros sessions. With Saros only sharing resource trees, it
is not important whether the other side does not support the format of
transferred modules.

#### [INTERNAL][I] Do general migration of LocalFilesystemModificationHandler

Removes the calls to deprecated methods.

Adds a TODO to clean up the remaining module-specific logic.

#### [REFACTOR][I] Clean up VirtualFileConverter

Removes the methods dealing with the old file implementation from
VirtualFileConverter.

Renames the new methods to their proper name.

### CODE REVIEW

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ intellij/src/saros/intellij/filesystem/VirtualFileConverter.java  -1
+ intellij/src/saros/intellij/editor/EditorManager.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5574769&bid=18276440)

**Comment by tobous** [comment]
Rebased onto current base branch resolving minor merge conflicts.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ intellij/src/saros/intellij/editor/EditorManager.java  -1
+ intellij/src/saros/intellij/filesystem/VirtualFileConverter.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5574769&bid=18276440)

**Comment by tobous** [comment]
Rebased onto current master without any interaction.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ intellij/src/saros/intellij/filesystem/VirtualFileConverter.java  -1
+ intellij/src/saros/intellij/editor/EditorManager.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5574769&bid=18276440)

**Pull request merged**
