### PR TITLE
Clean up after migration to reference points (ref-point migration 4/5)

### PR DESCRIPTION
**Pull request by tobous**
Cleans up after the migration to use the new reference point based resource implementations. This PR does not contain any changes to the logic but rather just updates class/variable/method names, javadoc, other comments, and some of the messages displayed to the user. It also removes the old resource implementations as they are no longer used.

I would suggest reviewing this PR commit by commit.

#### [REFACTOR][I] Rename IntelliJVersionProvider

Removes the capitalization of the trailing J of "IntelliJ" to match the
general naming of IntelliJ classes.

#### [REFACTOR][I] Move classes of saros.project.* into saros.filesystem

Removes VirtualFileMock as it was no longer being used.

#### [REFACTOR][I] Rename IntelliJPathImpl and IntelliJWorkspaceImpl

Renames IntelliJPathImpl and IntelliJWorkspaceImpl to match the general
naming scheme.

#### [REFACTOR][I] Replace references to old sharing logic in UI package

### CODE REVIEW

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- intellij/src/saros/intellij/filesystem/IntellijPath.java  4
- intellij/src/saros/intellij/ui/wizards/pages/referencepointselection/ReferencePointSelectionResult.java  1
- intellij/src/saros/intellij/filesystem/AbstractIntellijResource.java  4
- intellij/src/saros/intellij/ui/menu/SarosResourceShareGroup.java  8
- intellij/src/saros/intellij/filesystem/SharedResourcesManager.java  6
- intellij/src/saros/intellij/filesystem/PathFactory.java  5
- intellij/src/saros/intellij/context/IntellijVersionProvider.java  3
- intellij/src/saros/intellij/ui/wizards/pages/referencepointselection/SelectLocalReferencePointRepresentationPage.java  4
- intellij/test/junit/saros/intellij/filesystem/IntellijPathTest.java  1
- intellij/src/saros/intellij/filesystem/IntellijFolder.java  9
- intellij/src/saros/intellij/filesystem/IntellijReferencePoint.java  7
- intellij/src/saros/intellij/filesystem/IntellijFile.java  8
- intellij/src/saros/intellij/ui/wizards/pages/referencepointselection/ReferencePointTab.java  8
- intellij/src/saros/intellij/filesystem/IntellijWorkspace.java  1
- intellij/src/saros/intellij/ui/wizards/AddReferencePointToSessionWizard.java  10
         

Clones added
============
- intellij/src/saros/intellij/filesystem/IntellijPath.java  2
- intellij/test/junit/saros/intellij/filesystem/IntellijPathTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5574778&bid=18276469)

**Comment by tobous** [comment]
Rebased onto current base branch resolving minor merge conflicts.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- intellij/src/saros/intellij/ui/wizards/pages/referencepointselection/ReferencePointSelectionResult.java  1
- intellij/src/saros/intellij/context/IntellijVersionProvider.java  3
- intellij/src/saros/intellij/ui/wizards/pages/referencepointselection/SelectLocalReferencePointRepresentationPage.java  4
- intellij/src/saros/intellij/filesystem/AbstractIntellijResource.java  5
- intellij/src/saros/intellij/filesystem/IntellijFile.java  8
- intellij/src/saros/intellij/filesystem/IntellijPath.java  4
- intellij/src/saros/intellij/filesystem/PathFactory.java  5
- intellij/src/saros/intellij/filesystem/SharedResourcesManager.java  6
- intellij/test/junit/saros/intellij/filesystem/IntellijPathTest.java  1
- intellij/src/saros/intellij/filesystem/IntellijFolder.java  9
- intellij/src/saros/intellij/filesystem/IntellijWorkspace.java  1
- intellij/src/saros/intellij/ui/menu/SarosResourceShareGroup.java  8
- intellij/src/saros/intellij/ui/wizards/pages/referencepointselection/ReferencePointTab.java  8
- intellij/src/saros/intellij/ui/wizards/AddReferencePointToSessionWizard.java  10
- intellij/src/saros/intellij/filesystem/IntellijReferencePoint.java  7
         

Clones added
============
- intellij/src/saros/intellij/filesystem/IntellijPath.java  2
- intellij/test/junit/saros/intellij/filesystem/IntellijPathTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5574778&bid=18276469)

**Comment by tobous** [comment]
Rebased onto current master only resolving minor merge conflicts.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- intellij/src/saros/intellij/filesystem/PathFactory.java  5
- intellij/src/saros/intellij/filesystem/IntellijFolder.java  9
- intellij/src/saros/intellij/filesystem/IntellijReferencePoint.java  7
- intellij/src/saros/intellij/ui/wizards/pages/referencepointselection/SelectLocalReferencePointRepresentationPage.java  4
- intellij/src/saros/intellij/filesystem/IntellijPath.java  4
- intellij/src/saros/intellij/ui/wizards/AddReferencePointToSessionWizard.java  10
- intellij/src/saros/intellij/ui/wizards/pages/referencepointselection/ReferencePointSelectionResult.java  1
- intellij/src/saros/intellij/filesystem/IntellijWorkspace.java  1
- intellij/src/saros/intellij/filesystem/IntellijFile.java  8
- intellij/src/saros/intellij/filesystem/AbstractIntellijResource.java  5
- intellij/src/saros/intellij/ui/menu/SarosResourceShareGroup.java  8
- intellij/src/saros/intellij/filesystem/SharedResourcesManager.java  6
- intellij/src/saros/intellij/context/IntellijVersionProvider.java  3
- intellij/src/saros/intellij/ui/wizards/pages/referencepointselection/ReferencePointTab.java  8
- intellij/test/junit/saros/intellij/filesystem/IntellijPathTest.java  1
         

Clones added
============
- intellij/src/saros/intellij/filesystem/IntellijPath.java  2
- intellij/test/junit/saros/intellij/filesystem/IntellijPathTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5574778&bid=18276469)

**Pull request merged**
