### PR TITLE
Core/permissions/add user privileges

### PR DESCRIPTION
**Pull request by Memo2109**
@stefaus  @m273d15 ok, next try to show you my idea of the user privilege extension. Let me know how you think about it.

### CODE REVIEW

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 38
           

Complexity increasing per file
==============================
- core/test/junit/saros/session/SarosSessionUserTest.java  1
- server/src/saros/server/console/ServerConsole.java  1
- core/src/saros/session/UserPrivilege.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/saros/saros/pullRequest?prid=4553990&bid=15318023)

**Comment by Memo2109** [comment]
@stefaus @m273d15 
Thank you very much steffan for your comments on the JavaCode. I'll improve my discrete and revise my code

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 8
           

Complexity increasing per file
==============================
- server/src/saros/server/console/ServerConsole.java  1
- core/test/junit/saros/session/SarosSessionUserTest.java  1
- core/src/saros/session/UserPrivilege.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/saros/saros/pullRequest?prid=4553990&bid=15318023)

**Comment by m273d15** [comment]
Is this the same as #772 ? Please apply the same comments as in #771 to this PR

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- server/src/saros/server/console/ServerConsole.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/saros/saros/pullRequest?prid=4553990&bid=15318023)

**Pull request closed without merging**
