### PR TITLE
[BUILD] Fix remaining "Unused*" violations

### PR DESCRIPTION
**Pull request by m273d15**
* Fix pmdTest violations
* Fix new violation

@stefaus I changed the method in ConnectionFailureHandler from private to public. Probably `@SuppressWarnings` is a better solution or implementing the interface via lambda. What do you think?

### CODE REVIEW

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5586574&bid=18307867)

**Comment by stefaus** [comment]
I think a SuppressWarnings make it more clear than changing it to public, but the easiest way as you proposed is probably a lambda https://gist.github.com/stefaus/e2ad89f6f2de2f8a7a92f9fb8c0d8c0f

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5586574&bid=18307867)

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5586574&bid=18307867)

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5586574&bid=18307867)

**Pull request merged**
