### PR TITLE
Clean up after resource implementation migration 1/2 (ref-point migration 7/10)

### PR DESCRIPTION
**Pull request by tobous**
Removes the old resource implementation and renames the new resource implementation to match the new naming scheme.

### CODE REVIEW

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- eclipse/src/saros/filesystem/EclipseFile.java  4
- eclipse/src/saros/filesystem/AbstractEclipseResource.java  5
- eclipse/src/saros/filesystem/EclipseReferencePoint.java  7
- eclipse/src/saros/filesystem/EclipseFolder.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5737000&bid=18766412)

**Comment by tobous** [comment]
Rebased onto current base branch without any interaction.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- eclipse/src/saros/filesystem/AbstractEclipseResource.java  5
- eclipse/src/saros/filesystem/EclipseReferencePoint.java  7
- eclipse/src/saros/filesystem/EclipseFolder.java  7
- eclipse/src/saros/filesystem/EclipseFile.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5737000&bid=18766412)

**Comment by tobous** [comment]
Rebased onto current base branch without any interaction.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- eclipse/src/saros/filesystem/AbstractEclipseResource.java  5
- eclipse/src/saros/filesystem/EclipseFolder.java  7
- eclipse/src/saros/filesystem/EclipseFile.java  4
- eclipse/src/saros/filesystem/EclipseReferencePoint.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5737000&bid=18766412)

**Review by srossbach — DISMISSED** [review]

**Comment by tobous** [comment]
Rebased onto current base branch without any interaction.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- eclipse/src/saros/filesystem/AbstractEclipseResource.java  5
- eclipse/src/saros/filesystem/EclipseFile.java  4
- eclipse/src/saros/filesystem/EclipseFolder.java  7
- eclipse/src/saros/filesystem/EclipseReferencePoint.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5737000&bid=18766412)

**Comment by tobous** [comment]
Rebased onto current base branch without any interactions.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- eclipse/src/saros/filesystem/EclipseFolder.java  7
- eclipse/src/saros/filesystem/AbstractEclipseResource.java  5
- eclipse/src/saros/filesystem/EclipseFile.java  4
- eclipse/src/saros/filesystem/EclipseReferencePoint.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5737000&bid=18766412)

**Comment by tobous** [comment]
Rebased onto current base branch without any interaction.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- eclipse/src/saros/filesystem/AbstractEclipseResource.java  5
- eclipse/src/saros/filesystem/EclipseFolder.java  7
- eclipse/src/saros/filesystem/EclipseFile.java  4
- eclipse/src/saros/filesystem/EclipseReferencePoint.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5737000&bid=18766412)

**Comment by tobous** [comment]
Rebased onto current master without any interaction.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- eclipse/src/saros/filesystem/EclipseFolder.java  7
- eclipse/src/saros/filesystem/EclipseFile.java  4
- eclipse/src/saros/filesystem/AbstractEclipseResource.java  5
- eclipse/src/saros/filesystem/EclipseReferencePoint.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=5737000&bid=18766412)

**Pull request merged**
