### PR TITLE
add mirror info

### PR DESCRIPTION
**Pull request by paul-hammant**

### CODE REVIEW

**Comment by koppor** [comment]
Is it also possible to enable "Issues" here? Seeing [teletype](https://teletype.atom.io/) getting more and more attraction, users will surely find the IntelliJ issue https://youtrack.jetbrains.com/issue/IDEABKL-708, which links to the saros project.

**Comment by fzieris** [comment]
@koppor Yes, we will enable GitHub's issue feature soon. We currently prepare the migration of our [Sourceforge bug tracker](https://sourceforge.net/p/dpp/bugs).

**Comment by koppor** [comment]
@fzieris Thank you for the backlink. For [JabRef](https://github.com/JabRef/jabref) we tried some sourceforge migration script and it looked good. However, a new repository was created. We also did not want to migrate all rusty bugs from https://sourceforge.net/p/jabref/bugs/. And thus decided against it.

**Comment by m273d15** [comment]
As of now GitHub hosts the main repository. Therefore the mirror info is not needed.

**Pull request closed without merging**
