### PR TITLE
Update to Eclipse 4.8

### PR DESCRIPTION
**Pull request by tobous**
#### [STF] Use renamed preference button

After eclipse 4.6 the button "Ok" was
renamed to "Apply and Close".

### CODE REVIEW

**Comment by tobous** [comment]
@m273d15 The tag was build successfully in dockerhub, so this should build now.

As mentioned in #795, my preferred option on how to proceed would be to merge this and fix the rest of the STF stuff (like #798) afterwards. But from what I heard from @m273d15, when also using #798, the STF runs successfully (excluding the small number of tests that are known to be broken).

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ eclipse/src/saros/ui/widgets/viewer/session/XMPPSessionDisplayComposite.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=4790104&bid=15949493)

**Comment by tobous** [comment]
@m273d15 Is there a reason to include the commits from #798 again?

**Comment by m273d15** [comment]
Ah, this was a mistake I noticed this PR after rebasing the branch. I will remove the commits.

**Comment by tobous** [comment]
The previous STF build (including the commits of #798) shows that it runs mostly successfully:
[Action result](https://github.com/saros-project/saros/commit/394fa8ff954d1a0f069de0a0b8e63e4d279c9976/checks?check_suite_id=391852607)
[Gradle build result](https://scans.gradle.com/s/7gqiwajpeytn6)

(More tests fail in the latest build as it is missing the contact view fix.)

**Comment by tobous** [comment]
@m273d15 Any objection on merging this?

**Pull request merged**
