### PR TITLE
[UI][E] Fix ConfigurationWizard's "Next" Button

### LINKED ISSUE #1016: "Next" button of the Saros Configuration Wizard not working
**Description**
The "Next" button of the wizard does not work (no action triggered)

**To Reproduce**
1. Open the Saros Configuration Wizard
2. Enter JID and Password
3. Click "Next"

**Expected behavior**
The next configuration dialog appears.

**Log files**
<details>
java.lang.NullPointerException
	at saros.ui.wizards.dialogs.ConfigurationWizardDialog.firePageChanging(ConfigurationWizardDialog.java:55)
	at org.eclipse.jface.wizard.WizardDialog.doPageChanging(WizardDialog.java:930)
	at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1214)
	at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:917)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:468)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at saros.ui.util.WizardUtils$3.call(WizardUtils.java:115)
	at saros.ui.util.WizardUtils$3.call(WizardUtils.java:1)
	at saros.ui.util.SWTUtils$1.run(SWTUtils.java:148)
	at saros.util.ThreadUtils$1.run(ThreadUtils.java:34)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4561)
	at saros.ui.util.SWTUtils.runSafeSWTSync(SWTUtils.java:172)
	at saros.ui.util.SWTUtils.runSWTSync(SWTUtils.java:142)
	at saros.ui.util.WizardUtils.openSarosConfigurationWizard(WizardUtils.java:109)
	at saros.ui.commandHandlers.StartSarosConfigurationHandler.execute(StartSarosConfigurationHandler.java:12)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
</details>

**Environment:**
 - Tested in: IDE Eclipse 2020-03
 - Saros Version 16.0.0

### PR DESCRIPTION
**Pull request by m273d15**
Fixes #1016

### CODE REVIEW

**Comment by m273d15** [comment]
I think about releasing a 16.0.1 (16.0.0 + cherry-pick this Commit), because
the wizard is important for new users.

**Comment by tobous** [comment]
Could you explain why this works? I don't quite understand why the added check helps.

**Comment by m273d15** [comment]
AFAIK the `createButtonsForButtonBar` is called during the dialog initialization (it creates the buttons "Next", "Finish",...).

In `createButtonsForButtonBar` the creation of the `createAccountButton` is conditional and is only created `if (CreateXMPPAccountWizard.CREATE_DIALOG_ENABLED)`. Therefore `createAccountButton` is `null` if `CREATE_DIALOG_ENABLED == false` (our current default value).

However, clicking on `Next` triggers the method `firePageChanging` that tries to call `setVisibile` on `createAccountButton` (which is `null`) and an NPE is thrown and `super.firePageChanging(event);` (change the page) is not called.

Furthermore, I think that the button creation logic should be part of a WizardPage and not the WizardDialog.

**Comment by m273d15** [comment]
Added a short description to the commit message.

**Pull request merged**
